---
- name: info vm demo
  hosts: all
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: get VM info
      community.vmware.vmware_guest_info:
        hostname: 192.168.4.206
        username: superuser@vsphere.local
        password: Poppyleon1!
        datacenter_name: "C-Ways Production Cluster"
        validate_certs: false
        name: VP-Sharegate
